### ISSUE TITLE
Expected liquidprompt version incorrect

### ISSUE THREAD

**Issue by yorffuoj** [nojhan/lp-dotmatrix#2]
Hello,
After your talk at the Capitole du Libre, I'm trying LiquidPrompt and your theme dotmatrix.
I followed the LiquidPrompt installation guide and it works well. The I downloaded your theme and sourced all the files as written in the README but I got the following error messages when running `lp_theme dotmatrix`:
```
_lp_version_greatereq: command not found
_lp_join: command not found
WARNING: the DotMatrix theme requires Liquid Prompt >= 2.2.0, but you have version , some features will not work and the prompt may crash.
_lp_ram_color: command not found
_lp_disk_color: command not found
_lp_fill: command not found
_lp_env_vars: command not found
_lp_cmake: command not found
_lp_modules: command not found
_lp_os: command not found
_lp_fill: command not found
_lp_ram_color: command not found
_lp_disk_color: command not found
_lp_fill: command not found
_lp_env_vars: command not found
_lp_cmake: command not found
_lp_modules: command not found
_lp_os: command not found
_lp_fill: command not found
_lp_ram_color: command not found
_lp_disk_color: command not found
_lp_fill: command not found
_lp_env_vars: command not found
_lp_cmake: command not found
_lp_modules: command not found
_lp_os: command not found
_lp_fill: command not found
_lp_error_meaning: command not found
_lp_ram_color: command not found
_lp_disk_color: command not found
_lp_fill: command not found
_lp_env_vars: command not found
_lp_cmake: command not found
_lp_modules: command not found
_lp_os: command not found
_lp_fill: command not found
_lp_error_meaning: command not found
```
We can see that several private functions are not present and the 3d line also shows that A version of LiquidPrompt over the v2.2.0 is required even though the last LiquidPrompt stable release is the v2.1.2. We can also see that the current version of my LiquidPrompt installation is not detected (`but you have version ,`)

I hope you can help me with this mess, I was really hyped with your talk!

**Comment by nojhan** [comment]
Yes, indeed the latest DotMatrix version requires the latest Liquid Prompt version.

So you should either clone Liquid Prompt's Git repository or download the [v2.2 release candidate](https://github.com/liquidprompt/liquidprompt/releases/tag/v2.2.0-rc.1) (which contains all those functions, like the LP version itself).

**Comment by yorffuoj** [comment]
Ok it works now but I got another problem, special characters don't display well
`X  stan    ~`
And if I `echo $PS1` I get `\[\]X \[\] \[\]stan \[\] \[\] \[\] \[\]~ \[\]\[\] \[\]\[\]\[\]\[\] \[\]\[\]\[\]` which is really weird. Do I miss some config in my terminal?

Here's the picture:
![image](https://github.com/nojhan/lp-dotmatrix/assets/47420551/6a19c35d-a2cf-4cf4-ae49-7b73b72a81d6)

**Comment by nojhan** [comment]
You need to configure your terminal emulator so that it will use a patched font having the non-standard powerline glyphs. I suggest one of the [Nerd fonts](https://www.nerdfonts.com/).

**Comment by nojhan** [comment]
Or you may as well use the default config or the `presets/variant-text.conf` one.

**Comment by nojhan** [comment]
@yorffuoj How did it go? Should I consider this fixed?

**Comment by yorffuoj** [comment]
Hello! Sorry I forgot to come back to you after I did it. It works like a charm now. It can be closed. Thanks a lot
